services:
  - type: web
    name: second-lease-backend
    env: python
    runtime: python3.11
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app

    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres:SecondLease2025@db.hqgurqbvesjqnthfzccc.supabase.co:5432/postgres"
      - key: JWT_SECRET_KEY
        value: "TSBgIFkgciBnIG4gSyBQIDEgYyBwICQgeyBoIEggaiBtIDQgSiBYIEAgeCBLIG0gNiA> IDAgayB9IC4gcSA>"
    autoDeploy: true